"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Footer = void 0;
var React = require("react");
require("./Footer.css");
var Footer = function () {
    return React.createElement("footer", { className: "mainfooter", role: "contentinfo" },
        React.createElement("div", { className: "footer-middle" },
            React.createElement("div", { className: "container" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-md-3 col-sm-6" },
                        React.createElement("div", { className: "footer-pad" },
                            React.createElement("h4", null, "About"),
                            React.createElement("ul", { className: "list-unstyled" },
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" })),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Payment Center")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Contact Directory")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Forms")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "News and Updates")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "FAQs"))))),
                    React.createElement("div", { className: "col-md-3 col-sm-6" },
                        React.createElement("div", { className: "footer-pad" },
                            React.createElement("h4", null, "Contact Us"),
                            React.createElement("ul", { className: "list-unstyled" },
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Website Tutorial")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Accessibility")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Disclaimer")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Privacy Policy")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "FAQs")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Webmaster"))))),
                    React.createElement("div", { className: "col-md-3 col-sm-6" },
                        React.createElement("div", { className: "footer-pad" },
                            React.createElement("h4", null, "Stores & Grocery"),
                            React.createElement("ul", { className: "list-unstyled" },
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Parks and Recreation")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Public Works")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Police Department")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Fire")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }, "Mayor and City Council")),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" }))))),
                    React.createElement("div", { className: "col-md-3" },
                        React.createElement("h4", null, "Follow Us"),
                        React.createElement("ul", { className: "social-network social-circle" },
                            React.createElement("li", null,
                                React.createElement("a", { href: "#", className: "icoFacebook", title: "Facebook" },
                                    React.createElement("i", { className: "fa fa-facebook" }))),
                            React.createElement("li", null,
                                React.createElement("a", { href: "#", className: "icoLinkedin", title: "Linkedin" },
                                    React.createElement("i", { className: "fa fa-linkedin" })))))),
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-md-12 copy" },
                        React.createElement("p", { className: "text-center" }, "\u00A9 Copyright 2022 - Distributed Store.  All rights reserved."))))));
};
exports.Footer = Footer;
//# sourceMappingURL=Footer.js.map